[theme]
theme = "/home/oruud/.config/sway/srcery.toml"
[icons]
icons = "/home/oruud/.config/sway/awesome.toml"

#[[block]]
#block = "watson"

[[block]]
block = "packages"
package_manager = ["pacman", "aur"]
interval = 6000
error_interval = 500
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "yay -Qua"
signal = 13

[[block]]
block = "custom"
json = true
signal = 12
command = """
[[ -e "/tmp/newsboatsyncicon_oruud" ]] \
	&& echo '{"state":"Info","text":"'$(cat /tmp/newsboatsyncicon_$USER)'"}' \
	|| echo '{}'
"""

[[block]]
block = "notmuch"
query = "tag:unread and tag:inbox"
maildir = "~/.local/share/mail"
threshold_info = 3
threshold_warning = 10
threshold_critical = 20
signal = 14

#[[block]]
#block = "music"
#player = "spotify"
#format = "$icon {$combo.str(max_w:20,rot_interval:0.5)|} "

[[block]]
block = "bluetooth"
mac = "60:AB:D2:65:5F:7A"
format = "$icon swimr"
disconnected_format = ""

[[block]]
block = "bluetooth"
mac = "F8:4E:17:E0:20:CC"
format = "$icon WH-1000XM4"
disconnected_format = ""

[[block]]
block = "bluetooth"
mac = "2C:41:A1:83:12:64"
format = "$icon bosie"
disconnected_format = ""

[[block]]
block = "bluetooth"
mac = "74:5C:4B:6C:49:0B"
format = "$icon jabbie"
disconnected_format = ""

[[block]]
block = "sound"

[[block]]
block = "net"
interval = 5
format = "$icon {$ip|No IP-address} via {'$ssid'|$device}"
missing_format = " ^icon_net no network "

[[block]]
block = "memory"
#format = " $icon $mem_used.eng(w:1,prefix:M)/$mem_total.eng(w:1,prefix:M) ($mem_used_percents.eng(w:2))"
format = " $icon $mem_used.eng(w:1,prefix:M)/$mem_total.eng(w:1,prefix:M)"

[[block]]
block = "load"
format = " $icon $1m.eng(w:3)"

[[block]]
block = "cpu"
format = " $icon $utilization"
format_alt = " $icon $frequency.eng(){ $boost.str()|}"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R', l:nb_NO) "
short = " $icon $timestamp.datetime(f:%R) "
[[block.click]]
button = "left"
cmd = "alacritty --class floater -e ikhal"

[[block]]
block = "privacy"
[[block.driver]]
name = "v4l"
[[block.driver]]
name = "pipewire"

[[block]]
block = "custom"
json = true
interval = 1
command = """
[[ "$(bluetoothctl show | rg 'Powered:' | cut -d ' ' -f 2)" == "yes" ]] \
	&& echo '{"icon":"bluetooth","state":"Good","text":""}' \
	|| echo '{"icon":"bluetooth","state":"Critical","text":""}'
"""
[[block.click]]
button = "left"
cmd = """
[[ "$(bluetoothctl show | rg 'Powered:' | cut -d ' ' -f 2)" == "yes" ]] \
	&& bluetoothctl power off \
	|| bluetoothctl power on
"""
