#!/bin/bash
#
# config-menu
#

exclude="UnityHub|unity3d|node_modules|whatsapp|whats-app|dotfiles|keybase|trello|slack|gimp|gtk|postman|wireshark|configstore|discord|draw.io|exercism|pulse|devcert"

choice=$(fd --type f --type l . "$XDG_CONFIG_HOME" | rg -iv "$exclude" | sed "s|$XDG_CONFIG_HOME/||g" | rofi -dmenu -no-custom -p "config")

if [[ "$choice" != "" ]]; then
  filename="$XDG_CONFIG_HOME/$choice"
  exec "$TERMINAL" --title "$(basename "$EDITOR") $filename" -e "$EDITOR" -f "$filename"
fi
