#!/bin/bash
#
# shortcuts
#

# Shell rc file (i.e. bash vs. zsh, etc.)
shellrc="$HOME/.zshrc"

# Config locations
folders="$HOME/.config/folders"


# Output locations
shell_shortcuts="$HOME/.config/shortcuts"
ranger_shortcuts="$HOME/.config/ranger/shortcuts.conf"
qute_shortcuts="$HOME/.config/qutebrowser/shortcuts.py"

# Remove
rm -f "$shell_shortcuts" "$ranger_shortcuts" "$qute_shortcuts"

explanation="Source generated folder shortcuts"

# Ensuring that output locations are properly sourced
(grep "source $shell_shortcuts"  "$shellrc")>/dev/null \
    || echo -e "\n# $explanation\nsource $shell_shortcuts" >> "$shellrc"

(grep "source $ranger_shortcuts" "$HOME/.config/ranger/rc.conf")>/dev/null \
    || echo -e "\n# $explanation\nsource $ranger_shortcuts" >> "$HOME/.config/ranger/rc.conf"

(grep "config.source(\"shortcuts.py\")" "$HOME/.config/qutebrowser/config.py")>/dev/null \
    || echo "config.source(\"shortcuts.py\")" >> "$HOME/.config/qutebrowser/config.py"

# Format the `folders` file in the correct syntax and sent it to all three configs.
sed "s/#.*$//;/^$/d" "$folders" | tee \
    >(awk '{print "alias g"$1"=\"cd "$2"\""}' >> "$shell_shortcuts") \
	>(awk '{print "config.bind(\";g"$1"\", \"set downloads.location.directory "$2"\")"}' >> "$qute_shortcuts") \
	| awk '{print "map g"$1" cd "$2"\nmap t"$1" tab_new "$2"\nmap m"$1" shell mv -v %s "$2"\nmap Y"$1" shell cp -rv %s "$2}' >> "$ranger_shortcuts"
