#!/bin/bash
#
# music-controls
#

case "$1" in
  # Volume controls
  "up"       ) pamixer -i "$2" ;;
  "down"     ) pamixer -d "$2" ;;
  "mute"     ) pamixer -t      ;;
  "truemute" ) pamixer -m      ;;

  # Music controls
  "toggle"   ) mpc toggle      ;;
  "pause"    ) mpc pause       ;;
  "stop"     ) mpc stop        ;;
  "forward"  ) mpc seek +"$2"  ;;
  "back"     ) mpc seek -"$2"  ;;
  "next"     ) mpc next        ;;
  "prev"     ) mpc prev        ;;
  "replay"   ) mpc seek 0%     ;;
esac
