#!/bin/bash
#
# select-display
#

internal="eDP1"
external="HDMI1"

choices=("internal" "external" "dual" "duplicate" "manual")
chosen=$(printf "%s\n" "${choices[@]}" | rofi -dmenu -no-custom -l "${#choices[@]}" -p "display")

case "$chosen" in
	internal)  xrandr \
               --output "$internal" --auto \
               --output "$external" --off ;;
	external)  xrandr \
               --output "$external" --auto \
               --output "$internal" --off ;;
	dual)      xrandr \
               --output "$internal" --auto \
               --output "$external" --auto --right-of "$internal" ;;
	duplicate) xrandr \
               --output "$internal" --auto --same-as "$external" \
               --output "$external" --auto ;;
	manual)    arandr ;;
esac
